config/routes.rb
Rails.application.routes.draw do
  resources :kitchens, only: [:show, :update]
  resources :cocktails, only: [:index, :show, :create, :new]
  resources :users, only: [:show, :create, :new, :edit, :update]
  resources :reviews, only: [:new, :create, :edit, :update, :destroy]

  root 'cocktails#index'
 
  delete 'sessions/logout', to: 'sessions#logout', as: 'logout'
  get "/login", to: 'sessions#new', as: 'new_login'
  post '/login', to: 'sessions#login', as: 'login'
  get '/search', to: 'cocktails#search', as: 'search_page'
  get '/signup', to: 'users#new', as: 'signup'
  get 'sessions/home', to: 'sessions#home', as: 'home'
  get 'homepage/index'

end

app/models/add_cocktail_to_kitchen.rb
class AddCocktailToKitchen < ApplicationRecord
  belongs_to :cocktail
  belongs_to :kitchen
end

app/models/api.rb
# require 'rubygems'
# require 'httparty'

# class CocktailApi
#     include HTTParty
#     base_uri "www.thecocktaildb.com"
#     key_value = ENV['1a53f7da9bmsh55c76e76c5b5770p187d7fjsn910a9b05df55']

#     def self.search(value)
#         get("api/json/v1/1a53f7da9bmsh55c76e76c5b5770p187d7fjsn910a9b05df55/search.php?s=#{value}")
#     end

# end

# CocktailApi.search('vodka')

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    has_many :reviews
    has_many :add_cocktails_to_kitchens
    has_many :users, through: :reviews
    belongs_to :kitchen, optional: true

    def self.most_reviewed
        self.all.max{ |ct| ct.reviews.length }
    end

    def number_of_reviews
        self.reviews.length
    end

    def average_star_rating
        self.reviews.sum {|rv| rv.stars } / self.reviews.length
    end

    
end

app/models/kitchen.rb
class Kitchen < ApplicationRecord
  belongs_to :user
  has_many :cocktails
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :cocktail


  validates :stars, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_one :kitchen
    has_many :cocktails, through: :reviews

    has_secure_password

    validates :name, :password, :age, :email, presence: true
    validates :name, uniqueness: true
    validates :password, length: { in: 8..16 }
    validates :age, numericality: {greater_than: 20}

    #validates_confirmation_of :password, :on => :create
end

app/controllers/add_cocktail_to_kitchens_controller.rb
class AddCocktailToKitchensController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :current_user

    def current_user
        return unless session[:user_id]
        @current_user ||= User.find(session[:user_id])
    end

    def logged_in?
        current_user.id? != nil
    end

    def require_logged_in
        return redirect_to(controller: 'sessions', action: 'new') unless logged_in?
    end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController


COCKTAIL_IMAGES = [
    "https://untappd.akamaized.net/photos/2018_05_30/4814406928c1f11ef911c8857a0fb29d_640x640.jpeg",
    "https://untappd.akamaized.net/photos/2018_05_28/338d8879f6a96d7481df678d3f509d4d_640x640.jpg",
    "https://pbs.twimg.com/media/EOBQiBvWAAA5GLv.jpg",
    "https://i.pinimg.com/236x/31/57/9d/31579dfce1e9d67607be18ed3112188c--drinks-alcohol-alcoholic-beverages.jpg",
    "https://images.squarespace-cdn.com/content/v1/5ce849fdc95df000011ea5e7/1601943082136-NNB9QCGK0HKSWDE876NI/ke17ZwdGBToddI8pDm48kMtiXMEMZ8ID8MVhA-T_Qc9Zw-zPPgdn4jUwVcJE1ZvWQUxwkmyExglNqGp0IvTJZamWLI2zvYWH8K3-s_4yszcp2ryTI0HqTOaaUohrI8PIXpy3a2Cibo6eml5BpILeGX-BY3QvcZT7F317PmmzovI/R%26D+4.0.png?format=1000w",
    "https://rarbrewing-images.imgix.net/2019/11/DSC_2488.jpg?auto=compress%2Cformat&fit=crop&h=600&ixlib=php-1.2.1&w=600&wpsize=tile_strict&s=e83f8935b0f86178743880cefc091f6a",
    "https://www.sciencenews.org/wp-content/uploads/2020/05/050620_mt_beer_feat-1028x579.jpg",
    "https://stmedia.stimg.co/ctyp-092320-Beer-Issue-Getty.jpg?w=1200&h=630",
    "https://i.dailymail.co.uk/1s/2019/09/16/14/18535700-0-image-a-50_1568639482087.jpg",
    "https://media.wired.com/photos/5f066bb7af3d0a069fd1d63d/1:1/w_1800,h_1800,c_limit/Gear-Homebrew-630019103.jpg",
]

    def search
        if params[:search].blank?  
            redirect_to(cocktails_path, alert: "Empty field!") and return  
        else  
            @parameter = params[:search].downcase 
            @results = Cocktail.all.where("lower(drink) LIKE :search", search: "%#{@parameter}%")
        end  
    end

    def new
        @cocktail = Cocktail.new
    end

    def create
        @cocktail = Cocktail.new(cocktail_params)

        if @cocktail.valid?
            @cocktail.img_url = COCKTAIL_IMAGES.sample
            @cocktail.save
            redirect_to cocktails_path
        else
            flash[:ct_errors] = @cocktail.errors.full_messages
            redirect_to new_cocktail_path
        end
    end
    
    def index
        @cocktails = Cocktail.all
    end


    def show
        @cocktail = Cocktail.find(params[:id])
    end


    private

    def cocktail_params
        params.require(:cocktail).permit(:drink, :alcohol_percentage, :description)
    end


    # def request_api(url)
    #   response = Excon.get(
    #     url,
    #     headers: {
    #       'X-RapidAPI-Host' => URI.parse(url).host,
    #       'X-RapidAPI-Key' => ENV.fetch('1a53f7da9bmsh55c76e76c5b5770p187d7fjsn910a9b05df55')
    #     }
    #   )
    #   return nil if response.status != 200
    #   JSON.parse(response.body)
    # end
    # def find_cocktail(name)
    #   request_api(
    #     "https://www.thecocktaildb.com/api/json/v1/1/search.php?s=#{URI.encode(name)}"
    #   )
    # end
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController

    def update
    end

    def show
        @kitchen = Kitchen.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def new
        @review = Review.new
    end
    
    def create
        @review = Review.create(review_params)
        if @review.valid?
            @current_user.reviews << @review
            redirect_to kitchen_path(@current_user.kitchen)
        else
            flash[:review_errors] = @review.errors.full_messages
            redirect_to new_review_path
        end
    end

    def edit
        @review = Review.find(params[:id])
    end

    def update
        @review = Review.find(params[:id])
        @review.update(review_params)
        redirect_to kitchen_path(@review.user.kitchen)
    end

    def destroy
        @review = Review.find(params[:id])
        @review.destroy
        flash[:notice] = "Review Deleted!"
        redirect_to kitchen_path(@current_user.kitchen)
    end

    private

    def review_params
        params.require(:review).permit(:content, :stars, :user_id, :cocktail_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def home
    end

    def logout
        session.delete :user_id

        redirect_to root_path
    end

    def login
        user = User.find_by(name: params[:session][:name])
        user = user.try(:authenticate, params[:session][:password])

        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id 
            redirect_to kitchen_path(user)
        else
            flash[:errors] = "Username or Password are incorrect"
            redirect_to new_login_path
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        user = User.create(user_params)

        if user.valid?
            session[:user_id] = user.id
            Kitchen.create(user: user)
            redirect_to kitchen_path(user.kitchen)
        else
            flash[:user_errors] = user.errors.full_messages
            redirect_to new_user_path
        end
    end

    def edit
        @user = User.find(current_user.id)
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        redirect_to @user
    end

    private

    def user_params
        params.require(:user).permit(:name, :password, :email, :age)
    end

end

app/helpers/add_cocktail_to_kitchens_helper.rb
module AddCocktailToKitchensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/kitchens_helper.rb
module KitchensHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cocktails/index.html.erb
<head>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
  </head>


<h1 class="animate__animated animate__zoomInDown new-brew-form">Welcome to Brew!</h1>


<div class='index-container'>
    <% @cocktails.each do |ct| %>


        <div class='index-tile'>
        <%= image_tag ct.img_url, class: 'index-img' %>
        <p><%= link_to ct.drink, cocktail_path(ct) %></p>
        <% if @current_user %>
            <a href="http://localhost:3000/reviews/new?" class="btn btn-warning">Leave a review!</a>
            <% else %>
            <a href="http://localhost:3000/login" class="btn btn-warning">Login/Signup to leave a review!</a>
            <% end %>
        </div>
    <% end %>
</div>

app/views/cocktails/new.html.erb
<h1 class="new-brew">Add your own drink!</h1>

<p class="new-brew">With this form you can add your own drink of choice to our system</p>
<p class="new-brew">Just provide us with a few details about your drink below</p>

<div class='new-brew-form'>
    <%= form_for @cocktail do |f| %>
        <label for="drink" class="label">Drink Name</label>
        <%= f.text_field :drink, class: "form-control" %>
        <br>
        <%= f.label :alcohol_percentage %>
        <%= f.text_field :alcohol_percentage, class: "form-control" %>
        <br>
        <%= f.label :brand %>
        <%= f.text_field :brand, class: "form-control" %>
        <br>
        <%= f.label :style %>
        <%= f.text_field :style, class: "form-control" %>
        <br>
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
        <br>
        <%= f.submit "Submit", class: "btn btn-warning" %>
    <% end %>
</div>

app/views/cocktails/search.html.erb
<% if @results.length > 0 %>
    <h3 class="new-brew-form">Here are the drinks we could find that matched..</h3>  

   <div class='index-container'>
    <% @results.each do |result| %>
        <div class='index-tile'>
        <%= image_tag result.img_url, class: 'index-img' %>
        <p><%= link_to result.drink, cocktail_path(result) %></p>
        <% if @current_user %>
           <p><%= button_to "Review this drink", new_review_path, method: :get, class: 'btn btn-warning' %></p>
        <% else %>
        <p><%= button_to "Login/Signup to add this to your Kitchen", new_login_path, method: 'get', class: 'btn btn-warning' %></p>
        <% end %>
        </div>
    <% end %>
</div>

<% else %>
    <h3 class="new-brew-form">Sorry we couldn't find that drink!</h3>
    <h4 class="new-brew-form">Add this drink with NewBrew or try another search</h4>
<% end %>

app/views/cocktails/show.html.erb
<div class='new-brew-form'>
    <%= image_tag @cocktail.img_url, class: 'index-img' %>
    <h1><%= @cocktail.drink %>

    <h3><strong>Percentage: </strong><%= @cocktail.alcohol_percentage %></h3>

    <h5><strong>Brand: </strong><%= @cocktail.brand %></h5>
    
    <h6><strong>Style: </strong><%= @cocktail.style %></h6>

    <p><strong>Description: </strong><%= @cocktail.description %></p>
    <% if @cocktail.reviews.length > 0 %>
        <p><strong>Average BrewRating: </strong><%= @cocktail.average_star_rating %> star(s)</p>

    <% if @current_user %>
        <a href="http://localhost:3000/reviews/new?" class="btn btn-warning">Review this drink!</a>
    <% else %>
        <p><%= button_to "Login/Signup to review this drink", login_path, class: "btn btn-warning", method: 'get' %></p>
    <% end %>

    <% else %>
        <% if @current_user %>
            <a href="http://localhost:3000/reviews/new?" class="btn btn-warning">Review this drink!</a>
        <% else %>
            <p><%= button_to "Login/Signup to review this drink", login_path, class: "btn btn-warning", method: 'get' %></p>
        <% end %>
    <% end %>
</div>

app/views/kitchens/show.html.erb
<h1 class="kitchen-header">Welcome to Your Kitchen</h1>
<% if @current_user.reviews.length > 0 %>
    <h3 class="kitchen-header">Here are some of your current reviews</h3>
<% else %>
    <h3 class="kitchen-header">Your Reviews will show up here!</h3>
<% end %>
<div class='index-container'>
<% @current_user.cocktails.each do |ct| %>
    <div class='index-tile'>
    <%= image_tag ct.img_url, class: 'index-img' %>
    <h5><%= ct.drink %></h5>
    <% ct.reviews.each do |review| %>
      <p><%= review.content %></p>
       <p><%= review.stars %> star(s)!</p>
       <%= button_to "Edit This Review", edit_review_path(review), method: :get, class: 'btn btn-warning' %>
       <br>
       <br>
       <%= button_to  "Delete This Review", review_path(review), method: :delete, class: 'btn btn-warning', data: { confirm: 'Are you sure you want to delete this drink review?' }%>
       <hr>
    <% end %>
    </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Slurp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!--Nav Bar/Logo/Links on top of page begins here! (: -->
    <nav class="navbar navbar-default">
      <div class="nav navbar-nav">
        <a href="http://localhost:3000/cocktails">
          <img src="https://www.freelogodesign.org/download/file?id=2127417c-38e2-4e52-9181-b36d1f7315b9_200x200.png" alt="Picture Broken" style="max-height: 150px" class="py-2 px-2"  >
        </a>
        <a class="navbar-burger" id="burger">
          <span></span>
          <span></span>
          <span></span>
        </a>
      </div>
      
      <%= form_tag(search_page_path, :method => "get", class: 'navbar-form navbar-left', action: '/search') do %>
      <div class="input-group">
      <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
      <div class="input-group-btn">
      <%= button_tag "FindBrew", :class => 'btn btn-warning glyphicon glyphicon-search',:name => nil%>  
    </div>
  </div>
<% end %>
  
      <div class="nav navbar-nav"></div>
          <a href="/cocktails" class="navbar-item">Home</a>
            <% if @current_user %>
              <%= link_to "My Kitchen", @current_user.kitchen %>
              <%= link_to "NewBrew", new_cocktail_path %>
              <%= link_to "BrewReview", new_review_path %>
              <%= link_to "Logout", logout_path, method: :delete  %></li>
            <% else %>
              <a href="/users/new" class="navbar-item">Signup</a>
              <a href="/login" class="navbar-item">Login</a>
            <% end %>
        </div>
      </div>
    </nav>
  
    <script src="/app/index.js"></script>
    
    
    
    
    
    
    <%= yield %>
  </body>
</html>

app/views/reviews/edit.html.erb
    <div class='new-brew-form'>
    <h1>Change this review</h1>

    <%= form_for @review do |f| %>
        <%= f.label :cocktail_id %><br />
        <%= f.collection_select :cocktail_id, Cocktail.all, :id, :drink %><br />

        <%= f.label :stars %>
        <div class="rating_selection">

        <%= f.radio_button :stars, 1 %> 
        <label for="review_rating_1">
        <span>⭐</span></label>
        <br>
        <%= f.radio_button :stars, 2 %> 
        <label for="review_rating_2">
        <span>⭐⭐</span></label>
        <br>
        <%= f.radio_button :stars, 3 %> 
        <label for="review_rating_3">
        <span>⭐⭐⭐</span></label>
        <br>
        <%= f.radio_button :stars, 4 %> 
        <label for= "review_rating_4">
        <span>⭐⭐⭐⭐</span></label>
        <br>
        <%= f.radio_button :stars, 5 %> 
        <label for="review_rating_5">
        <span>⭐⭐⭐⭐⭐</span></label>
    <br />
    
    <%= f.label :content %><br />
        <%= f.text_area :content %>
        <%= f.hidden_field :user_id, value: @current_user.id  %>
    <br />
        <%= f.submit "Review", class: "btn btn-warning", style: "margin-top: 10px;" %>
    <% end %>
<br>
</div>

app/views/reviews/new.html.erb
<h1 class='new-brew-form'>Review a Drink</h1>

<h3 class='new-brew-form'>Tell us how you liked this drink!</h3>
<div class="new-brew-form">
    <%= form_for @review do |f| %>

    <label for="cocktail">Which drink would you like to review?</label>
    <br>
    <%= f.collection_select :cocktail_id, Cocktail.all, :id, :drink, prompt: true%><br />
    <label for="stars">How many stars for this drink?</label>
    <div class="rating_selection">

    <%= f.radio_button :stars, 1 %> 
    <label for="review_rating_1">
    <span>⭐</span></label>
    <br>
    <%= f.radio_button :stars, 2 %> 
    <label for="review_rating_2">
    <span>⭐⭐</span></label>
    <br>
    <%= f.radio_button :stars, 3 %> 
    <label for="review_rating_3">
    <span>⭐⭐⭐</span></label>
    <br>
    <%= f.radio_button :stars, 4 %> 
    <label for= "review_rating_4">
    <span>⭐⭐⭐⭐</span></label>
    <br>
    <%= f.radio_button :stars, 5 %> 
    <label for="review_rating_5">
    <span>⭐⭐⭐⭐⭐</span></label>
</div>


    <label for="content">How did you enjoy this drink?</label>
    <br />
    <%= f.text_area :content%>
    <br />
     <%= f.hidden_field :user_id, value: @current_user.id  %>
    <%= f.submit "Review", class: "btn btn-warning", style: "margin-top: 10px;" %>
    <% end %>


<% if flash[:review_errors] %>
    <% flash[:review_errors].each do |error| %>
    <p style="color:black;"><%=error%></p>
    <%end%>
<%end%>

</div>
<br>

app/views/users/edit.html.erb
<div class="new-brew-form">
    <% if flash[:user_errors] %>
        <% flash[:user_errors].each do |error| %>
            <%= error %>
        <% end %>
    <% end %>
    <h1>Edit your profile details here</h1>
    <%= form_for @user do |f| %>
        <label>Username</label>
        <%= f.text_field :name %>
        <br>
        <br>
        <label for="password">New Password</label>
        <%= f.password_field :password %>
        <br>
        <br>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <br>
        <br>
        <%= f.label :age %>
        <%= f.number_field :age %>
        <br>
        <br>
    <%= f.submit class: "btn btn-warning"%>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <div id="new-user-form-container">     
                <div class="new-brew-form">
                    <% if flash[:user_errors] %>
                    <% flash[:user_errors].each do |error| %>
                    <p style="color:black;"><%=error%></p>
                    <%end%>
                    <%end%>
                
                
                <i class="fas fa-user-plus fa-3x"></i>
                <h1 id="new-user-header">New Drinker</h1>

                <div class="form-group">
                    <%= form_for @user, controller: 'users', action: 'update' do |f| %>
                    <label for="name">Username</label>
                    <%= f.text_field :name, class: "form-control" %>
                    <label for="password">Password</label>
                    <%= f.password_field :password, class: "form-control" %>
                    <%= f.label :email %>
                    <%= f.email_field :email, class: "form-control" %>
                    <label for="age">Age (must be 21 or older to join)</label>
                    <%= f.number_field :age, class: "form-control" %>
                    <br>
                    <%= f.submit "Submit", class: "btn btn-warning" %>
                    <% end %>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div id="new-user-picture-container">
                <div class="new-brew-form">
                    <h1 id="new-user-header-2">Lets find some new beers!</h1>
                    <h3 id="new-user-lead" class="lead">Please provide us with some info so we can create your account!</h3>
                </div>
            </div>
        </div>
    </div>
</div>
</body>       

app/views/users/show.html.erb
<div class="new-brew-form">
  <h1>Hello <%= @current_user.name %>. Here are your profile details</h1>
    
    <p class="class-text">Email: <%= @current_user.email%></p>
    
    <p class="class-text">Age: <%= @current_user.age%></p>
    
    <%= link_to "Edit Profile", edit_user_path(@current_user), class: "btn btn-warning" %>

    
</div>